spring:
  application:
    name: Spring-chatMemory
  datasource:
    url: jdbc:mysql://localhost:3306/al_chat?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci        #???? JDBC ????? utf8mb4 ?????? utf8mb4_unicode_ci ??
  ai:
    deepseek:
      api-key: sk-bda06bb0514a4adc8b33dfac2d26cc72
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
    chat:
      memory:
        repository:
          jdbc:
            platform: mariadb     #??jdbc????????????
            initialize-schema: always #???????????????????

server:
  port: 8081
