server:
  port: 8080
spring:
  application:
    name: spring-chat
  ai:
    deepseek:
      api-key: sk-bda06bb0514a4adc8b33dfac2d26cc72
      chat:
        options:
          model: deepseek-chat
          temperature: 0.8
        base-url: "https://api.deepseek.com/beta"